apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 3 # number of replicas to create
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-cont
        image: acrmatmanpoc2.azurecr.io/order:latest # replace with your web API image name
        imagePullPolicy: IfNotPresent # pull image only if it doesn't exist
        ports:
          - containerPort: 5035
            protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5035